// Autogenerated by Thrift Compiler (0.13.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package MPDCDS_BackendService

import (
	"bytes"
	"context"
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
	"reflect"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = context.Background
var _ = reflect.DeepEqual
var _ = bytes.Equal

type MPDCDS_BackendService interface { //
	//多协议数据采集和分配系统接口服务

	// 权限验证接口
	// 1:用户名
	// 2：密码
	// 返回值：token
	//
	//
	// Parameters:
	//  - User
	//  - Password
	Auth(ctx context.Context, user string, password string) (r string, err error)
	// 权限验证接口
	// 1:token
	// 2:pwd   当前目录地址
	// 返回值：目录和文件列表
	//
	//
	// Parameters:
	//  - Token
	//  - Pwd
	Lists(ctx context.Context, token string, pwd string) (r []map[string]string, err error)
	// 文件信息
	// 1:token
	// 2:pwd   当前目录地址
	// 3:path  文件名
	// 返回值：url size time name
	//
	// Parameters:
	//  - Pwd
	//  - Path
	File(ctx context.Context, pwd string, path string) (r map[string]string, err error)
}

//
//多协议数据采集和分配系统接口服务
type MPDCDS_BackendServiceClient struct {
	c thrift.TClient
}

func NewMPDCDS_BackendServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *MPDCDS_BackendServiceClient {
	return &MPDCDS_BackendServiceClient{
		c: thrift.NewTStandardClient(f.GetProtocol(t), f.GetProtocol(t)),
	}
}

func NewMPDCDS_BackendServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *MPDCDS_BackendServiceClient {
	return &MPDCDS_BackendServiceClient{
		c: thrift.NewTStandardClient(iprot, oprot),
	}
}

func NewMPDCDS_BackendServiceClient(c thrift.TClient) *MPDCDS_BackendServiceClient {
	return &MPDCDS_BackendServiceClient{
		c: c,
	}
}

func (p *MPDCDS_BackendServiceClient) Client_() thrift.TClient {
	return p.c
}

// 权限验证接口
// 1:用户名
// 2：密码
// 返回值：token
//
//
// Parameters:
//  - User
//  - Password
func (p *MPDCDS_BackendServiceClient) Auth(ctx context.Context, user string, password string) (r string, err error) {
	var _args0 MPDCDS_BackendServiceAuthArgs
	_args0.User = user
	_args0.Password = password
	var _result1 MPDCDS_BackendServiceAuthResult
	if err = p.Client_().Call(ctx, "auth", &_args0, &_result1); err != nil {
		return
	}
	return _result1.GetSuccess(), nil
}

// 权限验证接口
// 1:token
// 2:pwd   当前目录地址
// 返回值：目录和文件列表
//
//
// Parameters:
//  - Token
//  - Pwd
func (p *MPDCDS_BackendServiceClient) Lists(ctx context.Context, token string, pwd string) (r []map[string]string, err error) {
	var _args2 MPDCDS_BackendServiceListsArgs
	_args2.Token = token
	_args2.Pwd = pwd
	var _result3 MPDCDS_BackendServiceListsResult
	if err = p.Client_().Call(ctx, "lists", &_args2, &_result3); err != nil {
		return
	}
	return _result3.GetSuccess(), nil
}

// 文件信息
// 1:token
// 2:pwd   当前目录地址
// 3:path  文件名
// 返回值：url size time name
//
// Parameters:
//  - Pwd
//  - Path
func (p *MPDCDS_BackendServiceClient) File(ctx context.Context, pwd string, path string) (r map[string]string, err error) {
	var _args4 MPDCDS_BackendServiceFileArgs
	_args4.Pwd = pwd
	_args4.Path = path
	var _result5 MPDCDS_BackendServiceFileResult
	if err = p.Client_().Call(ctx, "file", &_args4, &_result5); err != nil {
		return
	}
	return _result5.GetSuccess(), nil
}

type MPDCDS_BackendServiceProcessor struct {
	processorMap map[string]thrift.TProcessorFunction
	handler      MPDCDS_BackendService
}

func (p *MPDCDS_BackendServiceProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
	p.processorMap[key] = processor
}

func (p *MPDCDS_BackendServiceProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
	processor, ok = p.processorMap[key]
	return processor, ok
}

func (p *MPDCDS_BackendServiceProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
	return p.processorMap
}

func NewMPDCDS_BackendServiceProcessor(handler MPDCDS_BackendService) *MPDCDS_BackendServiceProcessor {

	self6 := &MPDCDS_BackendServiceProcessor{handler: handler, processorMap: make(map[string]thrift.TProcessorFunction)}
	self6.processorMap["auth"] = &mPDCDS_BackendServiceProcessorAuth{handler: handler}
	self6.processorMap["lists"] = &mPDCDS_BackendServiceProcessorLists{handler: handler}
	self6.processorMap["file"] = &mPDCDS_BackendServiceProcessorFile{handler: handler}
	return self6
}

func (p *MPDCDS_BackendServiceProcessor) Process(ctx context.Context, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	name, _, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return false, err
	}
	if processor, ok := p.GetProcessorFunction(name); ok {
		return processor.Process(ctx, seqId, iprot, oprot)
	}
	iprot.Skip(thrift.STRUCT)
	iprot.ReadMessageEnd()
	x7 := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function "+name)
	oprot.WriteMessageBegin(name, thrift.EXCEPTION, seqId)
	x7.Write(oprot)
	oprot.WriteMessageEnd()
	oprot.Flush(ctx)
	return false, x7

}

type mPDCDS_BackendServiceProcessorAuth struct {
	handler MPDCDS_BackendService
}

func (p *mPDCDS_BackendServiceProcessorAuth) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := MPDCDS_BackendServiceAuthArgs{}
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
		oprot.WriteMessageBegin("auth", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return false, err
	}

	iprot.ReadMessageEnd()
	result := MPDCDS_BackendServiceAuthResult{}
	var retval string
	var err2 error
	if retval, err2 = p.handler.Auth(ctx, args.User, args.Password); err2 != nil {
		x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing auth: "+err2.Error())
		oprot.WriteMessageBegin("auth", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return true, err2
	} else {
		result.Success = &retval
	}
	if err2 = oprot.WriteMessageBegin("auth", thrift.REPLY, seqId); err2 != nil {
		err = err2
	}
	if err2 = result.Write(oprot); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.Flush(ctx); err == nil && err2 != nil {
		err = err2
	}
	if err != nil {
		return
	}
	return true, err
}

type mPDCDS_BackendServiceProcessorLists struct {
	handler MPDCDS_BackendService
}

func (p *mPDCDS_BackendServiceProcessorLists) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := MPDCDS_BackendServiceListsArgs{}
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
		oprot.WriteMessageBegin("lists", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return false, err
	}

	iprot.ReadMessageEnd()
	result := MPDCDS_BackendServiceListsResult{}
	var retval []map[string]string
	var err2 error
	if retval, err2 = p.handler.Lists(ctx, args.Token, args.Pwd); err2 != nil {
		x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing lists: "+err2.Error())
		oprot.WriteMessageBegin("lists", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return true, err2
	} else {
		result.Success = retval
	}
	if err2 = oprot.WriteMessageBegin("lists", thrift.REPLY, seqId); err2 != nil {
		err = err2
	}
	if err2 = result.Write(oprot); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.Flush(ctx); err == nil && err2 != nil {
		err = err2
	}
	if err != nil {
		return
	}
	return true, err
}

type mPDCDS_BackendServiceProcessorFile struct {
	handler MPDCDS_BackendService
}

func (p *mPDCDS_BackendServiceProcessorFile) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := MPDCDS_BackendServiceFileArgs{}
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
		oprot.WriteMessageBegin("file", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return false, err
	}

	iprot.ReadMessageEnd()
	result := MPDCDS_BackendServiceFileResult{}
	var retval map[string]string
	var err2 error
	if retval, err2 = p.handler.File(ctx, args.Pwd, args.Path); err2 != nil {
		x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing file: "+err2.Error())
		oprot.WriteMessageBegin("file", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return true, err2
	} else {
		result.Success = retval
	}
	if err2 = oprot.WriteMessageBegin("file", thrift.REPLY, seqId); err2 != nil {
		err = err2
	}
	if err2 = result.Write(oprot); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.Flush(ctx); err == nil && err2 != nil {
		err = err2
	}
	if err != nil {
		return
	}
	return true, err
}

// HELPER FUNCTIONS AND STRUCTURES

// Attributes:
//  - User
//  - Password
type MPDCDS_BackendServiceAuthArgs struct {
	User     string `thrift:"user,1" db:"user" json:"user"`
	Password string `thrift:"password,2" db:"password" json:"password"`
}

func NewMPDCDS_BackendServiceAuthArgs() *MPDCDS_BackendServiceAuthArgs {
	return &MPDCDS_BackendServiceAuthArgs{}
}

func (p *MPDCDS_BackendServiceAuthArgs) GetUser() string {
	return p.User
}

func (p *MPDCDS_BackendServiceAuthArgs) GetPassword() string {
	return p.Password
}
func (p *MPDCDS_BackendServiceAuthArgs) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField1(iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(fieldTypeId); err != nil {
					return err
				}
			}
		case 2:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField2(iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *MPDCDS_BackendServiceAuthArgs) ReadField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.User = v
	}
	return nil
}

func (p *MPDCDS_BackendServiceAuthArgs) ReadField2(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.Password = v
	}
	return nil
}

func (p *MPDCDS_BackendServiceAuthArgs) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("auth_args"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(oprot); err != nil {
			return err
		}
		if err := p.writeField2(oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *MPDCDS_BackendServiceAuthArgs) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("user", thrift.STRING, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:user: ", p), err)
	}
	if err := oprot.WriteString(string(p.User)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.user (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:user: ", p), err)
	}
	return err
}

func (p *MPDCDS_BackendServiceAuthArgs) writeField2(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("password", thrift.STRING, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:password: ", p), err)
	}
	if err := oprot.WriteString(string(p.Password)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.password (2) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:password: ", p), err)
	}
	return err
}

func (p *MPDCDS_BackendServiceAuthArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MPDCDS_BackendServiceAuthArgs(%+v)", *p)
}

// Attributes:
//  - Success
type MPDCDS_BackendServiceAuthResult struct {
	Success *string `thrift:"success,0" db:"success" json:"success,omitempty"`
}

func NewMPDCDS_BackendServiceAuthResult() *MPDCDS_BackendServiceAuthResult {
	return &MPDCDS_BackendServiceAuthResult{}
}

var MPDCDS_BackendServiceAuthResult_Success_DEFAULT string

func (p *MPDCDS_BackendServiceAuthResult) GetSuccess() string {
	if !p.IsSetSuccess() {
		return MPDCDS_BackendServiceAuthResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *MPDCDS_BackendServiceAuthResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MPDCDS_BackendServiceAuthResult) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 0:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField0(iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *MPDCDS_BackendServiceAuthResult) ReadField0(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 0: ", err)
	} else {
		p.Success = &v
	}
	return nil
}

func (p *MPDCDS_BackendServiceAuthResult) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("auth_result"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField0(oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *MPDCDS_BackendServiceAuthResult) writeField0(oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err := oprot.WriteFieldBegin("success", thrift.STRING, 0); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 0:success: ", p), err)
		}
		if err := oprot.WriteString(string(*p.Success)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.success (0) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 0:success: ", p), err)
		}
	}
	return err
}

func (p *MPDCDS_BackendServiceAuthResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MPDCDS_BackendServiceAuthResult(%+v)", *p)
}

// Attributes:
//  - Token
//  - Pwd
type MPDCDS_BackendServiceListsArgs struct {
	Token string `thrift:"token,1" db:"token" json:"token"`
	Pwd   string `thrift:"pwd,2" db:"pwd" json:"pwd"`
}

func NewMPDCDS_BackendServiceListsArgs() *MPDCDS_BackendServiceListsArgs {
	return &MPDCDS_BackendServiceListsArgs{}
}

func (p *MPDCDS_BackendServiceListsArgs) GetToken() string {
	return p.Token
}

func (p *MPDCDS_BackendServiceListsArgs) GetPwd() string {
	return p.Pwd
}
func (p *MPDCDS_BackendServiceListsArgs) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField1(iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(fieldTypeId); err != nil {
					return err
				}
			}
		case 2:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField2(iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *MPDCDS_BackendServiceListsArgs) ReadField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.Token = v
	}
	return nil
}

func (p *MPDCDS_BackendServiceListsArgs) ReadField2(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.Pwd = v
	}
	return nil
}

func (p *MPDCDS_BackendServiceListsArgs) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("lists_args"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(oprot); err != nil {
			return err
		}
		if err := p.writeField2(oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *MPDCDS_BackendServiceListsArgs) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("token", thrift.STRING, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:token: ", p), err)
	}
	if err := oprot.WriteString(string(p.Token)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.token (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:token: ", p), err)
	}
	return err
}

func (p *MPDCDS_BackendServiceListsArgs) writeField2(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("pwd", thrift.STRING, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:pwd: ", p), err)
	}
	if err := oprot.WriteString(string(p.Pwd)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.pwd (2) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:pwd: ", p), err)
	}
	return err
}

func (p *MPDCDS_BackendServiceListsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MPDCDS_BackendServiceListsArgs(%+v)", *p)
}

// Attributes:
//  - Success
type MPDCDS_BackendServiceListsResult struct {
	Success []map[string]string `thrift:"success,0" db:"success" json:"success,omitempty"`
}

func NewMPDCDS_BackendServiceListsResult() *MPDCDS_BackendServiceListsResult {
	return &MPDCDS_BackendServiceListsResult{}
}

var MPDCDS_BackendServiceListsResult_Success_DEFAULT []map[string]string

func (p *MPDCDS_BackendServiceListsResult) GetSuccess() []map[string]string {
	return p.Success
}
func (p *MPDCDS_BackendServiceListsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MPDCDS_BackendServiceListsResult) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 0:
			if fieldTypeId == thrift.LIST {
				if err := p.ReadField0(iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *MPDCDS_BackendServiceListsResult) ReadField0(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return thrift.PrependError("error reading list begin: ", err)
	}
	tSlice := make([]map[string]string, 0, size)
	p.Success = tSlice
	for i := 0; i < size; i++ {
		_, _, size, err := iprot.ReadMapBegin()
		if err != nil {
			return thrift.PrependError("error reading map begin: ", err)
		}
		tMap := make(map[string]string, size)
		_elem8 := tMap
		for i := 0; i < size; i++ {
			var _key9 string
			if v, err := iprot.ReadString(); err != nil {
				return thrift.PrependError("error reading field 0: ", err)
			} else {
				_key9 = v
			}
			var _val10 string
			if v, err := iprot.ReadString(); err != nil {
				return thrift.PrependError("error reading field 0: ", err)
			} else {
				_val10 = v
			}
			_elem8[_key9] = _val10
		}
		if err := iprot.ReadMapEnd(); err != nil {
			return thrift.PrependError("error reading map end: ", err)
		}
		p.Success = append(p.Success, _elem8)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return thrift.PrependError("error reading list end: ", err)
	}
	return nil
}

func (p *MPDCDS_BackendServiceListsResult) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("lists_result"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField0(oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *MPDCDS_BackendServiceListsResult) writeField0(oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err := oprot.WriteFieldBegin("success", thrift.LIST, 0); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 0:success: ", p), err)
		}
		if err := oprot.WriteListBegin(thrift.MAP, len(p.Success)); err != nil {
			return thrift.PrependError("error writing list begin: ", err)
		}
		for _, v := range p.Success {
			if err := oprot.WriteMapBegin(thrift.STRING, thrift.STRING, len(v)); err != nil {
				return thrift.PrependError("error writing map begin: ", err)
			}
			for k, v := range v {
				if err := oprot.WriteString(string(k)); err != nil {
					return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
				}
				if err := oprot.WriteString(string(v)); err != nil {
					return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
				}
			}
			if err := oprot.WriteMapEnd(); err != nil {
				return thrift.PrependError("error writing map end: ", err)
			}
		}
		if err := oprot.WriteListEnd(); err != nil {
			return thrift.PrependError("error writing list end: ", err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 0:success: ", p), err)
		}
	}
	return err
}

func (p *MPDCDS_BackendServiceListsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MPDCDS_BackendServiceListsResult(%+v)", *p)
}

// Attributes:
//  - Pwd
//  - Path
type MPDCDS_BackendServiceFileArgs struct {
	Pwd  string `thrift:"pwd,1" db:"pwd" json:"pwd"`
	Path string `thrift:"path,2" db:"path" json:"path"`
}

func NewMPDCDS_BackendServiceFileArgs() *MPDCDS_BackendServiceFileArgs {
	return &MPDCDS_BackendServiceFileArgs{}
}

func (p *MPDCDS_BackendServiceFileArgs) GetPwd() string {
	return p.Pwd
}

func (p *MPDCDS_BackendServiceFileArgs) GetPath() string {
	return p.Path
}
func (p *MPDCDS_BackendServiceFileArgs) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField1(iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(fieldTypeId); err != nil {
					return err
				}
			}
		case 2:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField2(iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *MPDCDS_BackendServiceFileArgs) ReadField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.Pwd = v
	}
	return nil
}

func (p *MPDCDS_BackendServiceFileArgs) ReadField2(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.Path = v
	}
	return nil
}

func (p *MPDCDS_BackendServiceFileArgs) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("file_args"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(oprot); err != nil {
			return err
		}
		if err := p.writeField2(oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *MPDCDS_BackendServiceFileArgs) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("pwd", thrift.STRING, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:pwd: ", p), err)
	}
	if err := oprot.WriteString(string(p.Pwd)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.pwd (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:pwd: ", p), err)
	}
	return err
}

func (p *MPDCDS_BackendServiceFileArgs) writeField2(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("path", thrift.STRING, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:path: ", p), err)
	}
	if err := oprot.WriteString(string(p.Path)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.path (2) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:path: ", p), err)
	}
	return err
}

func (p *MPDCDS_BackendServiceFileArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MPDCDS_BackendServiceFileArgs(%+v)", *p)
}

// Attributes:
//  - Success
type MPDCDS_BackendServiceFileResult struct {
	Success map[string]string `thrift:"success,0" db:"success" json:"success,omitempty"`
}

func NewMPDCDS_BackendServiceFileResult() *MPDCDS_BackendServiceFileResult {
	return &MPDCDS_BackendServiceFileResult{}
}

var MPDCDS_BackendServiceFileResult_Success_DEFAULT map[string]string

func (p *MPDCDS_BackendServiceFileResult) GetSuccess() map[string]string {
	return p.Success
}
func (p *MPDCDS_BackendServiceFileResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MPDCDS_BackendServiceFileResult) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 0:
			if fieldTypeId == thrift.MAP {
				if err := p.ReadField0(iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *MPDCDS_BackendServiceFileResult) ReadField0(iprot thrift.TProtocol) error {
	_, _, size, err := iprot.ReadMapBegin()
	if err != nil {
		return thrift.PrependError("error reading map begin: ", err)
	}
	tMap := make(map[string]string, size)
	p.Success = tMap
	for i := 0; i < size; i++ {
		var _key11 string
		if v, err := iprot.ReadString(); err != nil {
			return thrift.PrependError("error reading field 0: ", err)
		} else {
			_key11 = v
		}
		var _val12 string
		if v, err := iprot.ReadString(); err != nil {
			return thrift.PrependError("error reading field 0: ", err)
		} else {
			_val12 = v
		}
		p.Success[_key11] = _val12
	}
	if err := iprot.ReadMapEnd(); err != nil {
		return thrift.PrependError("error reading map end: ", err)
	}
	return nil
}

func (p *MPDCDS_BackendServiceFileResult) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("file_result"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField0(oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *MPDCDS_BackendServiceFileResult) writeField0(oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err := oprot.WriteFieldBegin("success", thrift.MAP, 0); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 0:success: ", p), err)
		}
		if err := oprot.WriteMapBegin(thrift.STRING, thrift.STRING, len(p.Success)); err != nil {
			return thrift.PrependError("error writing map begin: ", err)
		}
		for k, v := range p.Success {
			if err := oprot.WriteString(string(k)); err != nil {
				return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
			}
			if err := oprot.WriteString(string(v)); err != nil {
				return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
			}
		}
		if err := oprot.WriteMapEnd(); err != nil {
			return thrift.PrependError("error writing map end: ", err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 0:success: ", p), err)
		}
	}
	return err
}

func (p *MPDCDS_BackendServiceFileResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MPDCDS_BackendServiceFileResult(%+v)", *p)
}
